server:
  port: 8888
  ssl:
    enabled: false

spring:
  data:
    redis:
      host: localhost

management:
  tracing:
    sampling:
      probability: 0.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
