spring.application.name=greet-service
server.port=8081
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://tempo:4318/v1/traces
